minor

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -40,7 +40,7 @@ cpu_indexes_array=`echo "$gpu_detect_json" | jq -c '[ . | to_entries[] | select(
 ########################################################################################################################
 
 . agent.miner_stats.sh
-       
+
 . agent.do_command.sh
 
 ########################################################################################################################
@@ -56,12 +56,12 @@ function loop {
 
 	[ -z $MINER ] && MINER="claymore"
 	HIVE_URL="$HIVE_HOST_URL/worker/api"
-  
+
 	gpu_stats=`gpu-stats`
 	local temp=$(jq '.temp' <<< $gpu_stats)
 	local fan=$(jq '.fan' <<< $gpu_stats)
 	local power=$(jq '.power' <<< $gpu_stats)
-         
+
 
 	miner2_json=
 	if [[ ! -z $MINER2 ]]; then
@@ -70,20 +70,20 @@ function loop {
 		miner2_json=$(jq -n --arg miner2 "$MINER2" --arg total_khs2 "$khs" --argjson miner_stats2 "$stats" \
 			'{"params": {$miner2, $total_khs2, $miner_stats2}}')
 	fi
-         
+
 	miner_stats $MINER #khs and stats are global
 
 	echo -en "Hashrate ${CYAN}$MINER${NOCOLOR} `[[ $khs > 0 ]] && echo -e ${YELLOW} || echo -e ${RED}`$khs${NOCOLOR} kH/s"
 	[[ ! -z $MINER2 ]] &&
 		echo -en " ${CYAN}$MINER2${NOCOLOR} `[[ $khs2 > 0 ]] && echo -e ${YELLOW} || echo -e ${RED}`$khs2${NOCOLOR} kH/s"
-  echo -en "\n"
+	echo -en "\n"
 	echo $khs > /run/hive/khs
 
 
 
 	#echo $stats
 	#uptime: load averages for the past 1, 5, and 15 minutes
-  
+
 	request=$(
 	jq -n \
 	--arg rig_id "$RIG_ID" \
@@ -104,13 +104,13 @@ function loop {
 		}
 	}'
 	)
-  
+
 	[[ ! -z $miner2_json ]] && #add miner2 stats to json
 		request=`echo "$request" "$miner2_json" | jq -s '.[0] * .[1]'`
-  
+
 	echo $request | jq '.' -C -c
 
-  if [[ -z $RIG_ID ]]; then
+	if [[ -z $RIG_ID ]]; then
 		echo -e "${YELLOW}No RIG_ID, skipping sending stats${NOCOLOR}"
 		return
 	fi
@@ -122,24 +122,24 @@ function loop {
 	response=$(echo "$request" | curl --insecure -L --data @- \
 	--connect-timeout 7 --max-time 15 --silent \
 	-XPOST "${HIVE_URL}?id_rig=$RIG_ID&method=stats"  -H "Content-Type: application/json")
-  
+
 	exitcode=$?
 	if [[ $exitcode -ne 0 || -z $response ]]; then
 		echo -e "${RED}Error sending stats${NOCOLOR} $HIVE_HOST_URL" && human-curl-error $exitcode
 		echo "[`date`] < ERROR SENDING STATS TO $HIVE_HOST_URL (curl code=$exitcode) \"$response\"" >> $LOG
 		return $exitcode
 	fi
-  
+
 	#echo $response
 	#echo "[`date`] < `echo $response | jq '.' -c`" >> $LOG
 	echo "[`date`] < $response" >> $LOG #full response even invalid
-  
+
 	error=$(echo $response | jq '.error | select (.!=null)' --raw-output)
-  [[ $? != 0 ]] && echo -e "${RED}Invalid response${NOCOLOR}: $HIVE_HOST_URL\n$response" && return 1
-  [[ ! -z $error ]] && echo -e "${RED}Error response${NOCOLOR}: $error" && return 1
-  
+	[[ $? != 0 ]] && echo -e "${RED}Invalid response${NOCOLOR}: $HIVE_HOST_URL\n$response" && return 1
+	[[ ! -z $error ]] && echo -e "${RED}Error response${NOCOLOR}: $error" && return 1
+
 	command=$(echo "$response" | jq '.result.command' --raw-output| tr -dc '[:print:]')
-  
+
 	[[ $command != "OK" ]] && echo "$response" | jq '.result'
 
 	if [[ $command != "batch" ]]; then
diff --git a/hive/bin/hostname-check b/hive/bin/hostname-check
--- a/hive/bin/hostname-check
+++ b/hive/bin/hostname-check
@@ -14,12 +14,12 @@ if [[ ! -z $WORKER_NAME ]]; then
 	#starts with digits
 	[[ $hostname =~ ^([0-9]+).* ]] && hostname="hive$WORKER_NAME" #echo "${BASH_REMATCH[1]}"
 
-    #if ! grep -qE "127.0.0.1 .*\s+$WORKER_NAME" "/etc/hosts"; then
-    if ! grep -q "127.0.0.1 $hostname" "/etc/hosts"; then
-        #echo "Hostname missing in /etc/hosts, adding"
-        printf "\n127.0.0.1 $hostname\n" >> /etc/hosts
-    fi
-    #echo "WORKER_NAME=$WORKER_NAME"
-    #TODO Win?
-    #hostnamectl set-hostname "$hostname"
+	#if ! grep -qE "127.0.0.1 .*\s+$WORKER_NAME" "/etc/hosts"; then
+	if ! grep -q "127.0.0.1 $hostname" "/etc/hosts"; then
+		#echo "Hostname missing in /etc/hosts, adding"
+		printf "\n127.0.0.1 $hostname\n" >> /etc/hosts
+	fi
+	#echo "WORKER_NAME=$WORKER_NAME"
+	#TODO Win?
+	#hostnamectl set-hostname "$hostname"
 fi
diff --git a/hive/bin/net-test b/hive/bin/net-test
--- a/hive/bin/net-test
+++ b/hive/bin/net-test
@@ -26,63 +26,63 @@ CASE_WIDTH='%-64s'
 
 
 function PrintCase {
-    printf "$CASE_COLOR%-64s" "$1"
+	printf "$CASE_COLOR%-64s" "$1"
 }
 
 
 # ping wrapper
 function Ping {
 	LAST_RESULT=0
-    IP=$2
-    [ -z ${IP} ] && IP=$1
+	IP=$2
+	[ -z ${IP} ] && IP=$1
 
-    PrintCase "ping $1"
-    ping -q -c 1 -w 5 $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
-    return $LAST_RESULT
+	PrintCase "ping $1"
+	ping -q -c 1 -w 5 $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
+	return $LAST_RESULT
 }
 
 
 # curl wrapper
 function Curl {
 	LAST_RESULT=0
-    IP=$2
-    [ -z ${IP} ] && IP=$1
+	IP=$2
+	[ -z ${IP} ] && IP=$1
 
-    PrintCase "curl $1"
-    curl curl --insecure --connect-timeout 4 --max-time 10 $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
-    return $LAST_RESULT
+	PrintCase "curl $1"
+	curl curl --insecure --connect-timeout 4 --max-time 10 $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
+	return $LAST_RESULT
 }
 
 
 # nslookup wrapper
 function NSLookup {
 	LAST_RESULT=0
-    IP=$2
-    [ -z ${IP} ] && IP=$1
+	IP=$2
+	[ -z ${IP} ] && IP=$1
 
-    PrintCase "nslookup $1"
-    nslookup $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
-    return $LAST_RESULT
+	PrintCase "nslookup $1"
+	nslookup $IP > /dev/null 2>&1 && echo -e $OK || { LAST_RESULT=1; echo -e $FAIL; }
+	return $LAST_RESULT
 }
 
 
 # check host with dns resolving, ip, http, https cases
 function Connection {
 	LAST_RESULT=0
-    RESULT=0
-    host=$1
+	RESULT=0
+	host=$1
 
-    NSLookup $1 $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your DNS server $DNS"$NOCOLOR
+	NSLookup $1 $2
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your DNS server $DNS"$NOCOLOR
 
-    Ping $1 $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your connection settings"$NOCOLOR
+	Ping $1 $2
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your connection settings"$NOCOLOR
 
-    Curl "http://$1" $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTP connection failed. Please check Firewall rules or connection setup."$NOCOLOR
+	Curl "http://$1" $2
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTP connection failed. Please check Firewall rules or connection setup."$NOCOLOR
 
-    Curl "https://$1" $2
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection failed. Please check Firewall rules or connection setup."$NOCOLOR
+	Curl "https://$1" $2
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection failed. Please check Firewall rules or connection setup."$NOCOLOR
 
 	return $LAST_RESULT
 }
@@ -90,35 +90,35 @@ function Connection {
 
 # connections test cases
 function Connections {
-    echo -e "${YELLOW}Checking network connection:${NOCOLOR}"
-    Ping "$LOCAL_GW (Gateway)" $LOCAL_GW
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Failed to ping router. Please check your router and physical connection."$NOCOLOR
+	echo -e "${YELLOW}Checking network connection:${NOCOLOR}"
+	Ping "$LOCAL_GW (Gateway)" $LOCAL_GW
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Failed to ping router. Please check your router and physical connection."$NOCOLOR
 
-    Ping "$LOCAL_DNS (DNS)" $LOCAL_DNS
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your DNS server $LOCAL_DNS"$NOCOLOR
+	Ping "$LOCAL_DNS (DNS)" $LOCAL_DNS
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Please check your DNS server $LOCAL_DNS"$NOCOLOR
 
-    Ping "8.8.8.8 (Google DNS)" "8.8.8.8"
-    [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Failed to ping Google DNS. Please check your internet connection"$NOCOLOR
+	Ping "8.8.8.8 (Google DNS)" "8.8.8.8"
+	[ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"Failed to ping Google DNS. Please check your internet connection"$NOCOLOR
 
-    Connection "google.com"
+	Connection "google.com"
 
 
 	echo
-    echo -e "${YELLOW}Checking connection to Hive servers:${NOCOLOR}"
+		echo -e "${YELLOW}Checking connection to Hive servers:${NOCOLOR}"
 	echo
-    echo -e "${WHITE}>>> api.hiveos.farm${NOCOLOR}"
-    Connection "api.hiveos.farm"
-    Curl "https://api.hiveos.farm:8443" $2; [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) on port 8443 connection failed. Please check Firewall rules or connection setup."$NOCOLOR
-    #Curl "https://api.hiveos.farm:41282" $2; [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection on port 41282 failed. Please check Firewall rules or connection setup."$NOCOLOR
+		echo -e "${WHITE}>>> api.hiveos.farm${NOCOLOR}"
+		Connection "api.hiveos.farm"
+		Curl "https://api.hiveos.farm:8443" $2; [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) on port 8443 connection failed. Please check Firewall rules or connection setup."$NOCOLOR
+		#Curl "https://api.hiveos.farm:41282" $2; [ $LAST_RESULT -eq 1 ] && echo -e $ERROR_COLOR"HTTPS (SSL) connection on port 41282 failed. Please check Firewall rules or connection setup."$NOCOLOR
 	echo
-    echo -e "${WHITE}>>> paris.hiveos.farm${NOCOLOR}"
-    Connection "paris.hiveos.farm"
+		echo -e "${WHITE}>>> paris.hiveos.farm${NOCOLOR}"
+		Connection "paris.hiveos.farm"
 	echo
-    echo -e "${WHITE}>>> amster.hiveos.farm${NOCOLOR}"
-    Connection "amster.hiveos.farm"
+		echo -e "${WHITE}>>> amster.hiveos.farm${NOCOLOR}"
+		Connection "amster.hiveos.farm"
 	echo
-    echo -e "${WHITE}>>> helsinki.hiveos.farm${NOCOLOR}"
-    Connection "helsinki.hiveos.farm"
+		echo -e "${WHITE}>>> helsinki.hiveos.farm${NOCOLOR}"
+		Connection "helsinki.hiveos.farm"
 }
 
 
@@ -131,7 +131,7 @@ function Connections {
 
 # restarting network interfaces
 #function RestartNetworking {
-#    if [ $LAST_RESULT -eq 1 ]; 
+#    if [ $LAST_RESULT -eq 1 ];
 #    then
 #    	echo -ne "$WARN_COLOR    connections was fail: restart network"
 #    	LAST_RESULT=0
@@ -169,7 +169,7 @@ Connections
 #Connections
 
 # Traceroute to hosts for debuging if connections was not fixed
-#if [ $LAST_RESULT -eq 1 ]; 
+#if [ $LAST_RESULT -eq 1 ];
 #then
 #	sleep 5
 #	echo
